"""Create songs table

Revision ID: 2b8073e7d715
Revises: 38115c3e576c
Create Date: 2025-05-12 11:22:47.243771

"""

import sqlalchemy as sa
from alembic import op

from app.models import SCHEMA, environment

# revision identifiers, used by Alembic.
revision = "2b8073e7d715"
down_revision = "38115c3e576c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "songs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("artist", sa.String(length=100), nullable=False),
        sa.Column("genre", sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )

    if environment == "prod":
        op.execute(f"ALTER TABLE users SET SCHEMA {SCHEMA};")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("songs")
    # ### end Alembic commands ###
