"""Create playlists table

Revision ID: 38115c3e576c
Revises: 06cf8e73f30f
Create Date: 2025-05-12 11:21:05.411257

"""

import sqlalchemy as sa
from alembic import op

from app.models.db import SCHEMA, environment

# revision identifiers, used by Alembic.
revision = "38115c3e576c"
down_revision = "06cf8e73f30f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "playlists",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    if environment == "prod":
        op.execute(f"ALTER TABLE users SET SCHEMA {SCHEMA};")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("playlists")
    # ### end Alembic commands ###
