"""Create playlist_songs table

Revision ID: 974945f1f48a
Revises: 2b8073e7d715
Create Date: 2025-05-12 11:24:26.869857

"""

import sqlalchemy as sa
from alembic import op

from app.models.db import SCHEMA, environment

# revision identifiers, used by Alembic.
revision = "974945f1f48a"
down_revision = "2b8073e7d715"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "playlist_songs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("playlist_id", sa.Uuid(), nullable=False),
        sa.Column("song_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["playlist_id"],
            ["playlists.id"],
        ),
        sa.ForeignKeyConstraint(
            ["song_id"],
            ["songs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    if environment == "prod":
        op.execute(f"ALTER TABLE users SET SCHEMA {SCHEMA};")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("playlist_songs")
    # ### end Alembic commands ###
